os: osx
osx_image: xcode11
script: bash clovergit --travis
after_success:
- ".travis/updateRepo.sh"
deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file: ~/src/CloverBootloader/CloverPackage/sym/Clover-*.zip
  file: ~/src/CloverBootloader/CloverPackage/sym/CloverISO-*/*.iso
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: vectorsigma72/DailyClover
env:
  global:
    secure: RKs/4v6phKeYS8QHSWDg4E8sd65O3FppD0UgphqKg+dhzxeHqA53Pp9TAkHLk3gfThfXK50B7oIwsZzeqc+qYAhmSGHpoaK8Jhy7IMqpus7/McYIJPfdyOCTmlaDu8Ma2LZxEEKcfZNpSgdlXbnMkR1SzcDMpZfIBNYNbbt+5UUJoPx6sWllhEqTukvukwasadEzhFKRcJvZSEGY/TxhXPqcYOf2q/J8MIH+9RCtr7YacHEFBWXVYMt0ekWEQxu5uBG0+lordFup3MmGU4QrUfNhKhV1DGapOnrgbLTNYYfV1KQiCukpRPVnAikWU1D6ZRHCB/a/mstohZZCvHSloSgP17/tebRcBk2TII8JaMAVosxigmd2JonYv1jJsc5alKZL8tha+q99Gg+uG07p/R4KvlsnNkono2eu3x0oIBC7/eUwZLCKPftTas8lESndctWLwvt59dEAI3SUrWDFOHMZ5g5nzTJ9/1yqocLgxTmK1FJwhGsvDoYqZEMycOBq5hGKCzJZUyVHMCODQo4n/URGTN3UUGDQ4KD4knvwa7Wp8gAWFVgY1MxZCAJAK3Heb2ZSd0A5zfr/q6EZqFs3yotfkzG2wvd4S/9ET6kE6n+PrqnztV1255Ceg6gcw/hzOOEfLUUiyv1hHhZGbdjTdaEpvJYvGbOqookjhbydbIo=
