git:
  depth: false
os: osx
osx_image: xcode11

before_script:
  - mkdir -p ~/src/tools
  - cp -R .Scripts ~/src/tools/Scripts

script: travis_wait bash clovergit --travis

before_deploy:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
  - git config --global user.email "$GIT_EMAIL"
  - git config --global user.name "$GIT_NAME"
  - export CLOVER_REV=$(cat ~/src/CloverBootloader/vers.txt)
  - export CLOVER_HASH=$(git -C ~/src/CloverBootloader rev-parse --short HEAD)
  - export TRAVIS_TAG="${CLOVER_REV}-${CLOVER_HASH}"
  - git tag "${TRAVIS_TAG}"
  - rm -rf .build
  - mkdir -p .build
  - cp -R ~/src/CloverBootloader/CloverPackage/sym/Clover_v*.zip .build/
  - cp -R ~/src/CloverBootloader/CloverPackage/sym/CloverISO*.tar.lzma .build/
  - mv -f .build/*.pkg .build/"Clover_v2.5k_r$(cat ~/src/CloverBootloader/vers.txt)_$(git -C ~/src/CloverBootloader rev-parse --short HEAD).pkg"
  - mv -f .build/*.tar.lzma .build/"CloverISO-$(cat ~/src/CloverBootloader/vers.txt)_$(git -C ~/src/CloverBootloader rev-parse --short HEAD).tar.lzma"

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  overwrite: true
  name: $TRAVIS_TAG
  skip_cleanup: true
  api_key: "$GH_TOKEN"
  file_glob: true
  file: .build/*

  on:
    branch: master
    repo: vectorsigma72/DailyClover

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
  - secure: cFLxHNrKvALTJqCeyS48Tmfow485hgPrkCD80poqJnn+dWQunJz7sCwjjWzTlW9wjbaIyWDR2N5eAax0TK0GRXe2jK4Cn2zCdKkqIFZaYHN7EbTtUyG2JgUuy5eCG0E9PV7/zYXx2v7NEWk7Awe/879SyhCWMYJf96srbV1A65pvCjFrA04ZpucQ6NKOSoSPqr46kuUNPCV0NXh9Pq5rTDgds22BD8XRcPI5mE73cqELFd5Vw0Ds1WjONlRAW9NZCCFVVJhb5MYjkUMVCQzV0gG8klID1M7OcfFoAeQsc4P+GMMMUF6Z49N94Qj88PAtOe/bhRLSqZRgOgDyuf1OGVwK+9IytGZyyf+hY9winsF27kZGQv6PmkAOFD72qeetcVv83POseVandGiZvFxqM/KeWaYpwK2xdqaO9f2N+JDtynoBj1lhdg4sTnpzXW/7p69qn6wYPY8APIKiiRe5O+H2er8B+58DoQuQKrKin6iUkEQJsS37samrSK66xrFnpS8ahMmHVBhTEvOzsxeU0S50VxJ/xUjV5XTNQYiUKlAh6pjb39e1TDugwr6TZerX6Pf5slFOAsShbnFZOqgJzsrMFu61aGnGEc8m8GH7JlmC2j9xThgrVsuoG/n6gj0b158l/6KBecC9QvdD1awQkQNQMSnQTWpzs4IIS7/VIGM=
